### ISSUE TITLE
How to classify a document?

### ISSUE THREAD

**Issue by lucaputelli** [SAG-KeLP/kelp-full#13]
Can KeLP be used in order to classify an entire document written in natural language?
I've tried to do these steps:
- generating the syntax tree (TreeRepresentation) from each sentence of my document using the Stanford Parser module;
- assigning a class label to the trees;
- putting them in a dataset for training or testing;
- executing the classification algorithm with the TreeKernel.
My problem is that the classifier works to every single sentence as a separate example, losing the "document concept". Each sentence is classified, but how can I classify an entire document?

Thanks.

**Comment by SimoneFilice** [comment]
Hi Luca,

How many sentences are in the documents you want to classify? If it is a low number, let's say 3-4 sentences per document, you could connect the root nodes of the sentences of each document to a document root node, so that you will have a single large tree representing an entire document.

If you have very long documents, I am not sure whether using tree kernels is appropriate. The question is: _do you expect that your NLP task has important syntactic patterns you should capture using tree kernels?_ 

Best,
Simone

**Comment by Hareem-E-Sahar** [comment]
@lucaputelli so its the limitation of the Stanford Parser that it returns a tree per sentence? If we have a tree per document (e.g. from another parser) then you should not have a problem. Right?

**Comment by crux82** [comment]
Yes, if you have a tree per each document, you can apply the kernel functions. 

In any case, I would advise against the use of a tree kernel for very large documents (which could generate a tree with hundreds or thousands of nodes): the size of the representation space and the structural complexity of these (huge) trees could compromise the quality of your analysis.

Bests 

Danilo
