### ISSUE TITLE
Could kelp-input-generator process Chinese word ?

### ISSUE THREAD

**Issue by psychic0119** [SAG-KeLP/kelp-full#14]
Recently, I used KELP to analyze short text classification. However, I encountered the following problem.
 
1.	Could  kelp-input-generator analyze Chinese words?
2.	If I have the string already processed by Stanford Parser, how could I parse these data into tree presentation like LCT or GRCT? Just like: (ROOT(NP(NR 湯姆)(CC 和)(NR 傑利))(VP(ADVP(AD 正在))(PP(NP(NR 花園)))(PP(P 替)(NP(NR 花草)))(VP(VV 灌溉)))).
 
Thank you for help.

**Comment by SimoneFilice** [comment]
Hi,

Thanks for using KeLP. Below are the answers, hope they can help:

1. Natively kelp-input-generator supports only English by wrapping the English version of the Stanford Parser. If you want to parse Chinese text your can either create a new wrapper to a desired parser, or change the maven dependency so that you include the Chinese models of the Stanford Parser instead of the English ones (I tried this last option but I'm getting an error, I need to investigate more, but there should be a way)
2. LCT and GRCT formats are tree conversion of dependency graph formats. In your case it seems you have a constituency tree format. This is totally fine and you can directly instantiate a TreeRepresentation using you parsed string:

```
TreeRepresentation tree = new TreeRepresentation();
tree.setDataFromText("(ROOT(NP(NR 連戰)(CC 和)(NR 宋楚瑜))(VP(ADVP(AD 正在))(PP(NP(NR 花蓮)))(PP(P 替)(NP(NR 謝深山)))(VP(VV 輔選))))");
System.out.println(tree.getTextFromData());//You should get (NOTYPE##ROOT(NOTYPE##NP(NOTYPE##NR(NOTYPE##連戰))(NOTYPE##CC(NOTYPE##和))(NOTYPE##NR(NOTYPE##宋楚瑜)))(NOTYPE##VP(NOTYPE##ADVP(NOTYPE##AD(NOTYPE##正在)))(NOTYPE##PP(NOTYPE##NP(NOTYPE##NR(NOTYPE##花蓮))))(NOTYPE##PP(NOTYPE##P(NOTYPE##替))(NOTYPE##NP(NOTYPE##NR(NOTYPE##謝深山))))(NOTYPE##VP(NOTYPE##VV(NOTYPE##輔選)))))
```

Please let me know if you manage to solve point 1.

Best,
Simone

**Comment by psychic0119** [comment]
Hi Simone,

Thanks for your help. I am new in Java, so I am no familiar with some operation. 

  1. I don't know how to change the maven dependency. But I will find the solution continuously. If I find 
      the method to solve the error finally, I will share with you.
  2. How can I change the TreeRepresentation into DependencyGraph? Because TreeRepresentationGenerator.grctGenerator method need to put DependencyGraph, but tree.setDataFromText is TreeRepresentation. Or I misunderstood something?
` TreeRepresentation grctGenerator1 = TreeRepresentationGenerator.grctGenerator(parse, rg, ng, ig);`

Sorry for asking so much question, Thanks for your help a lot.

**Comment by SimoneFilice** [comment]
Hi,

1. After you cloned kelp-input-generator you should open the pom.xml file in the project directory and change the dependency for the stanford parser. According to what I found online the line to change should be the classifier field from _models_ to _models-chinese_, i.e.:

```
		<dependency>
			<groupId>edu.stanford.nlp</groupId>
			<artifactId>stanford-corenlp</artifactId>
			<version>3.7.0</version>
			<classifier>models-chinese</classifier>
		</dependency>
```
As I told you I tried this yesterday but I encountered an execution problem while instantiating the stanford parser. Please let me know if you manage to make it work.

2. [Dependency grammar](http://en.wikipedia.org/wiki/Dependency_grammar) and [constituency grammar](http://en.wikipedia.org/wiki/Phrase_structure_grammar) are two different formalisms and you cannot convert one into the other. If you want a dependency graph, you need to parse your sentence using a dependency parser. However, if you have already a constituency parser, I suggest to try to use it instead of a dependency one, at least for the beginning. Constituency trees are valid syntactic representations and you can effectively use them in tree kernel based models. I do it quite often in my research activities, see for instance [(Filice et al. 2015)](http://www.aclweb.org/anthology/P15-1097).

Cheers,
Simone
