### ISSUE TITLE
To make it possible to use a forest of trees for learning

### ISSUE THREAD

**Issue by bgalitsky** [SAG-KeLP/kelp-full#2]
When we create representations for paragraphs, we might need to produce multiple structures per text units - would be nice to be able to specify a set of trees.
A number of trees in a set may vary from paragraph to paragraph

**Comment by crux82** [comment]
Dear Boris, 

we are planning to release an additional java class, named SequenceExample. It is essentially a list of Example(s). Even if this object has been designed in order to enable the implementation of sequence labeling methods, we believe it can be used also to represent paragraphs (in terms of a list of trees). For instance, a paragraph can be represented as a SequenceExample consisting of a SimpleExample for each sentence of the paragraph. Each SimpleExample should contain a TreeRepresentation corrisponding to parse tree associated to the sentence it models. Then, you are required to implement a specific Kernel operating on the SequenceExample(s). Such kernel will contain the logic to decompose the similarity between two SequenceExample(s) to a series of kernel computations among the SimpleExamples they contain. This is somehow similar to what is performed by kernels operating on ExamplePair(s) (see https://github.com/SAG-KeLP/kelp-core/tree/master/src/main/java/it/uniroma2/sag/kelp/kernel/pairs).

Do you think this can fit your needs?

At this moment, the SequenceExample has not been release yet (we are still validating the code) but we are planning to release it during XMAS time. 

We will notify you when it will be release. 

Best regards 

Danilo & Simone

**Comment by crux82** [comment]
Dear Boris, 

the new version of KeLP now contains SequenceExample(s).
Please check the corresponding documentation in the brand new KeLP site: 

http://www.kelp-ml.org/?page_id=215

I am at your disposition for any further question

Best regards

Danilo

**Comment by bgalitsky** [comment]
Thanks a lot Danilo


 We need these things badly because otherwise we would have to use original Joahims' or Moschitti's modules in C which bring integration difficulties.


Please also consider using our github project at

https://github.com/bgalitsky/relevance-based-on-parse-trees

[https://avatars3.githubusercontent.com/u/1051120?v=3&s=400]<https://github.com/bgalitsky/relevance-based-on-parse-trees>

bgalitsky/relevance-based-on-parse-trees<https://github.com/bgalitsky/relevance-based-on-parse-trees>
github.com
Automatically exported from code.google.com/p/relevance-based-on-parse-trees





Regards

Boris

________________________________
